apiVersion: apps/v1
kind: Deployment
metadata:
  name: K{FEATURE-}name
  labels:
    app: K{FEATURE-}name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: K{FEATURE-}name
  template:
    metadata:
      name: K{FEATURE-}name
      labels:
        app: K{FEATURE-}name
    spec:
      containers:
        - name: K{FEATURE-}name
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
