apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: K{FEATURE-}mc
spec:
  domains:
    - K{FEATURE.}example.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: K{FEATURE-}K{VERSION.}ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: service-title
                port:
                  number: 80
