name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        target: [
          x86_64-unknown-linux-gnu,
          x86_64-unknown-linux-musl,
          armv7-unknown-linux-gnueabihf,
          armv7-unknown-linux-musleabihf,
          aarch64-unknown-linux-gnu,
          aarch64-unknown-linux-musl,
          x86_64-apple-darwin,
          aarch64-apple-darwin,
          x86_64-pc-windows-msvc
        ]
        extension: [ "" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Rename artifact
        run: |
          BIN_NAME=$(basename $(find target/${{ matrix.target }}/release -maxdepth 1 -type f -executable))
          mv target/${{ matrix.target }}/release/$BIN_NAME target/${{ matrix.target }}/release/${BIN_NAME}-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/*-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
